Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
Note=input('enter a note:    ')
print("🌺🌺🌺🌺" + Note + "🌺🌺🌺🌺")
